### PR TITLE
More deterministic builds enhancements

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by sschuberth** [comment]
I believe I already reviewed this series during our http://gerrithub.io/ experiments, did I?

**Comment by t-b** [comment]
@sschuberth Yes partly. It also includes all proposed changes from the http://gerrithub.io trial.

**Comment by sschuberth** [comment]
Thanks for the clarification.

**Comment by t-b** [comment]
@sschuberth Fixed the commit message.

**Pull request merged**
